<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root[
<!ELEMENT root (prediction+)>
<!ELEMENT prediction (sign, text)>
<!ELEMENT sign (#PCDATA)>
<!ELEMENT text (#PCDATA)>
]>

<root>
    <prediction>
        <sign>1</sign>
        <text>Возможны встречи, поездки и новые знакомства. Однако сегодня не следует преувеличивать свои возможности.</text>
    </prediction>
    <prediction>
        <sign>2</sign>
        <text>Звезды гарантируют вам успех в делах, возможны денежные поступления, интересные деловые предложения.</text>
    </prediction>
    <prediction>
        <sign>3</sign>
        <text>Успех ни в чем не гарантирован. Сегодня на поддержку со стороны также можно не рассчитывать, действовать придется самостоятельно.</text>
    </prediction>
    <prediction>
        <sign>4</sign>
        <text>Вы сможете преуспеть, добиться успехов в работе. Финансовые вопросы и личные проблемы смогут быть решены в вашу пользу.</text>
    </prediction>
    <prediction>
        <sign>5</sign>
        <text>В общении с коллегами избегайте фамильярности.</text>
    </prediction>
    <prediction>
        <sign>6</sign>
        <text>В общении с окружающими могут возникнуть спорные ситуации, когда предстоит отстаивать свою точку зрения.</text>
    </prediction>
    <prediction>
        <sign>7</sign>
        <text>Для этого требуются находчивость и изворотливость.</text>
    </prediction>
    <prediction>
        <sign>8</sign>
        <text>На успех в делах рассчитывать можно, но все придет только благодаря кропотливому труду и вашему желанию преуспеть.</text>
    </prediction>
    <prediction>
        <sign>9</sign>
        <text>Однако и эти результаты порадуют. Станет понятно, в каком направлении получится двигаться в ближайшей перспективе.</text>
    </prediction>
    <prediction>
        <sign>10</sign>
        <text>Первая половина дня будет насыщенным на события периодом. Придется заниматься не только своими, но и чужими делами.</text>
    </prediction>
    <prediction>
        <sign>11</sign>
        <text>Однако на работе вероятна резкая смена планов и условий, которая может доставить вам немало хлопот и неприятных минут.</text>
    </prediction>
</root>