<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root[
        <!ELEMENT root (prediction+)>
        <!ELEMENT prediction (sign, text)>
        <!ELEMENT sign (#PCDATA)>
        <!ELEMENT text (#PCDATA)>
        ]>

<root>
    <prediction>
        <sign>1</sign>
        <text>Благоприятный день. Если вы проявите инициативу и приложите усилия, то сможете многое в своей жизни изменить к лучшему.</text>
    </prediction>
    <prediction>
        <sign>2</sign>
        <text>Будьте практичны. Этот день может положить начало длительному благоприятному периоду, но произойдет это лишь в том случае, если вы будете прислушиваться к доводам здравого смысла и никому не позволите ввести вас в заблуждение.</text>
    </prediction>
    <prediction>
        <sign>3</sign>
        <text>Успех ни в чем не гарантирован. Сегодня на поддержку со стороны также можно не рассчитывать, действовать придется самостоятельно.</text>
    </prediction>
    <prediction>
        <sign>4</sign>
        <text>Все неоднозначно и противоречиво, напряженных моментов на этой неделе будет немало, а вам сейчас спокойствие не помешало бы.</text>
    </prediction>
    <prediction>
        <sign>5</sign>
        <text>Первая половина дня удачна. Вам часто везет, есть шанс одержать важные победы. Не бойтесь рисковать, поступать не так, как вы привыкли.</text>
    </prediction>
    <prediction>
        <sign>6</sign>
        <text>У вас есть шанс открыть для себя один или несколько новых источников дохода.</text>
    </prediction>
    <prediction>
        <sign>7</sign>
        <text>Эта неделя особенно хороша для творчества в любых его проявлениях.</text>
    </prediction>
    <prediction>
        <sign>8</sign>
        <text>Побольше общайтесь с любимым человеком, старайтесь выстроить свои планы таким образом, чтобы они учитывали его занятость. </text>
    </prediction>
    <prediction>
        <sign>9</sign>
        <text>Не исключено, что в ближайшие дни ваши планы будут снова и снова нарушаться из-за какого-то недомогания. </text>
    </prediction>
    <prediction>
        <sign>10</sign>
        <text>Отнеситесь к некоторой неповоротливости общественного транспорта с пониманием.</text>
    </prediction>
    <prediction>
        <sign>11</sign>
        <text>Вы рискуете оказаться на грани нервного срыва из-за постоянной погони за успехом. </text>
    </prediction>
</root>